name = "Jitterplot"
uuid = "11a35010-c0ec-4872-b837-b6a5a0b71a2f"
repo = "https://github.com/4SAnalyticsnModelling/Jitterplot.git"
authors = ["Symon@4SAnalyticsnModelling"]
email = ["4sanalyticsnmodelling@gmail.com"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
